export default {
    base: import.meta.url,
    main: 'lib/logic/logic.js',
    urls: [
        'lib/logic/README.md',
        'lib/logic/logic.js',
        'lib/logic/runtime.js',
        'lib/logic/tags.js',

        'lib/logic/acorn@8.15.0.js',
        'lib/logic/acorn-walk@8.3.4.js',
        'lib/logic/schedulers/BFS.js',
        'lib/logic/schedulers/DFS.js',
        'lib/logic/solution.js',
        'lib/logic/GoalSeries.js',
        'lib/logic/findall.js',
        'lib/logic/parser.js',
        'lib/logic/runtime.js',
        'lib/logic/solve.js',
        'lib/logic/repr.js',
        'lib/logic/tracer.js',
        'lib/logic/testShim.js',
        'lib/logic/testShim/tests/closure.js',
        'lib/logic/testShim/tests/closure-as-data.js',
        'lib/logic/testShim/tests/shadowing.js',
        'lib/logic/testShim/tests/destructuring.js',
        'lib/logic/testShim/tests/destructuring-body-defaults.js',
        'lib/logic/testShim/tests/destructuring-head-defaults.js',
        'lib/logic/testShim/tests/destructuring-expressions.js',
        'lib/logic/testShim/tests/tracer.js',
        'lib/logic/testShim/tests/typeof.js',
        'lib/logic/testShim/tests/facts.js',
        'lib/logic/testShim/tests/compiler-errors.js',
        'lib/logic/testShim/tests/builtins-config.js',
        'lib/logic/testShim/tests/builtins-compile.js',
        'lib/logic/testShim/tests/builtins-optional.js',
        'lib/logic/testShim/tests/builtins-is_ground.js',
        'lib/logic/testShim/tests/builtins-js.js',
        'lib/logic/testShim/tests/builtins-js-async.js',
        'lib/logic/testShim/tests/patterns-array.js',
        'lib/logic/testShim/tests/patterns-object.js',
        'lib/logic/testShim/tests/builtins-findall.js',
        'lib/logic/testShim/tests/dynamic-subgoal.js',
        'lib/logic/testShim/tests/grandparent.js',
        'lib/logic/testShim/tests/negation.js',
        'lib/logic/testShim/tests/parent.js',
        'lib/logic/testShim/tests/path-finding.js',
        'lib/logic/testShim/tests/schedulers.js',
        'lib/logic/testShim/tests/rule-destructuring.js',
        'lib/logic/testShim/tests/rule.js',
        'lib/logic/testShim/tests/unification.js',

        'lib/logic/compile/program.js',

        'lib/logic/compile/analyze/util/mangleImport.js',
        'lib/logic/compile/analyze/util/mangleName.js',
        'lib/logic/compile/analyze/util/findDeclaredVariables.js',
        'lib/logic/compile/analyze/util/findDeclaredFunctions.js',
        'lib/logic/compile/analyze/util/positionTracker.js',
        'lib/logic/compile/analyze/util/visit.js',
        'lib/logic/compile/analyze/program.js',

        'lib/logic/compile/transform/builtins/compile.js',
        'lib/logic/compile/transform/builtins/config.js',
        'lib/logic/compile/transform/builtins/optional.js',
        'lib/logic/compile/transform/builtins/findall.js',
        'lib/logic/compile/transform/builtins/is_ground.js',
        'lib/logic/compile/transform/builtins/js.js',
        'lib/logic/compile/transform/globals.js',
        'lib/logic/compile/transform/globals/Logic.js',
        'lib/logic/compile/transform/nodes/statements/FunctionDeclaration.js',
        'lib/logic/compile/transform/nodes/expressions/CallExpression.js',
        'lib/logic/compile/transform/nodes/expressions/UnaryExpression.js',
        'lib/logic/compile/transform/nodes/expression.js',
        'lib/logic/compile/transform/script.js',
        'lib/logic/compile/transform/module.js',
        'lib/logic/compile/transform/util/findFreeVariables.js',

        'lib/logic/compile/transform/Emitter.js',
        'lib/logic/compile/transform/exprs/block.js',
        'lib/logic/compile/transform/exprs/call.js',
        'lib/logic/compile/transform/exprs/clause.js',
        'lib/logic/compile/transform/exprs/debugger.js',
        'lib/logic/compile/transform/exprs/ground.js',
        'lib/logic/compile/transform/exprs/if.js',
        'lib/logic/compile/transform/exprs/iife.js',
        'lib/logic/compile/transform/exprs/infix.js',
        'lib/logic/compile/transform/exprs/js.js',
        'lib/logic/compile/transform/exprs/negation.js',
        'lib/logic/compile/transform/exprs/predicate.js',
        'lib/logic/compile/transform/exprs/switch.js',
        'lib/logic/compile/transform/exprs/unify.js',
        'lib/logic/compile/transform/exprs/value.js',

        'lib/logic/unify.js',
        'lib/logic/unify/README.md',
        'lib/logic/unify/ArrayPattern.js',
        'lib/logic/unify/ObjectPattern.js',
        'lib/logic/unify/Value.js',
        'lib/logic/unify/Trace.js',
        'lib/logic/unify/testShim.js',
        'lib/logic/unify/testShim/tests/arrays.js',
        'lib/logic/unify/testShim/tests/default.js',
        'lib/logic/unify/testShim/tests/objects.js',
        'lib/logic/unify/testShim/tests/simple.js',
        'lib/logic/vars.js',
    ],
}
