export default {
    base: import.meta.url,
    urls: [
        'globals/logic.js',

        'lib/logic/README.md',
        'lib/logic/logic.js',
        'lib/logic/tags.js',

        'lib/logic/acorn@8.15.0.js',
        'lib/logic/schedulers/BFS.js',
        'lib/logic/schedulers/DFS.js',
        'lib/logic/solution.js',
        'lib/logic/GoalSeries.js',
        'lib/logic/solve.js',
        'lib/logic/solve/testShim.js',
        'lib/logic/solve/testShim/tests/closure.js',
        'lib/logic/solve/testShim/tests/closure-as-data.js',
        'lib/logic/solve/testShim/tests/shadowing.js',
        'lib/logic/solve/testShim/tests/destructuring.js',
        'lib/logic/solve/testShim/tests/tracer.js',
        'lib/logic/solve/testShim/tests/facts.js',
        'lib/logic/solve/testShim/tests/builtins-is_ground.js',
        'lib/logic/solve/testShim/tests/patterns-array.js',
        'lib/logic/solve/testShim/tests/patterns-object.js',
        'lib/logic/solve/testShim/tests/builtins-findall.js',
        'lib/logic/solve/testShim/tests/dynamic-subgoal.js',
        'lib/logic/solve/testShim/tests/grandparent.js',
        'lib/logic/solve/testShim/tests/negation.js',
        'lib/logic/solve/testShim/tests/number.js',
        'lib/logic/solve/testShim/tests/parent.js',
        'lib/logic/solve/testShim/tests/path-finding.js',
        'lib/logic/solve/testShim/tests/schedulers.js',
        'lib/logic/solve/testShim/tests/rule-destructuring.js',
        'lib/logic/solve/testShim/tests/rule.js',
        'lib/logic/solve/testShim/tests/unification.js',

        'lib/logic/compile/program.js',

        'lib/logic/compile/analyze/util/mangleName.js',
        'lib/logic/compile/analyze/util/visit.js',
        'lib/logic/compile/analyze/scopes.js',
        'lib/logic/compile/analyze/clauses.js',
        'lib/logic/compile/analyze/program.js',

        'lib/logic/compile/transform/builtins/findall.js',
        'lib/logic/compile/transform/builtins/is_ground.js',
        'lib/logic/compile/transform/globals.js',
        'lib/logic/compile/transform/globals/Logic.js',
        'lib/logic/compile/transform/nodes/FunctionDeclaration.js',
        'lib/logic/compile/transform/nodes/UnaryExpression.js',
        'lib/logic/compile/transform/nodes/LogicalExpression.js',
        'lib/logic/compile/transform/nodes/BinaryExpression.js',
        'lib/logic/compile/transform/nodes/ExpressionStatement.js',
        'lib/logic/compile/transform/nodes/AssignmentExpression.js',
        'lib/logic/compile/transform/nodes/VariableDeclaration.js',
        'lib/logic/compile/transform/nodes/CallExpression.js',
        'lib/logic/compile/transform/predicate.js',
        'lib/logic/compile/transform/program.js',
        'lib/logic/compile/transform/util/trim.js',

        'lib/logic/compile/generate/predicate.js',
        'lib/logic/compile/generate/clause.js',
        'lib/logic/compile/generate/ops.js',
        'lib/logic/compile/generate/ops/compare.js',
        'lib/logic/compile/generate/ops/findall.js',
        'lib/logic/compile/generate/ops/is_ground.js',
        'lib/logic/compile/generate/ops/js.js',
        'lib/logic/compile/generate/ops/negation.js',
        'lib/logic/compile/generate/ops/subgoal.js',
        'lib/logic/compile/generate/ops/unify.js',
        'lib/logic/compile/generate/blocks/reference.js',
        'lib/logic/compile/generate/blocks/value.js',
        'lib/logic/compile/generate/blocks/subgoal.js',

        'lib/logic/unify.js',
        'lib/logic/unify/ObjectPattern.js',
        'lib/logic/unify/ArrayPattern.js',
        'lib/logic/unify/pattern.js',
        'lib/logic/unify/testShim.js',
        'lib/logic/unify/testShim/tests/objects.js',
        'lib/logic/unify/testShim/tests/lists.js',
        'lib/logic/unify/testShim/tests/precedence.js',
        'lib/logic/unify/testShim/tests/simple.js',
        'lib/logic/vars.js',
    ],
}
